<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "catalogue_slg"
 *
 * Auto generated by Extension Builder 2017-01-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Catalogue_SLG',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Gregory Prince, Loïc Gouttefangeas, Sébastien Marcou',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);